name: 'ReviewBot'
description: 'A GitHub Action to automate code review process.'
inputs: 
  openapi-key:
    description: 'OpenAPI key'
    required: false
  openapi-model:
    description: 'OpenAPI model'
    required: false
    default: 'gpt-4o'
  gemini-key:
    description: 'Gemini key'
    required: false
  gemini-model:
    description: 'Gemini model'
    required: false
    default: 'gemini-1.5-flash-latest'
  github-token:
    description: 'GitHub token'
    required: true
runs:
  using: 'node20'
  main: 'compiled/index.js'
  