name: 'ReviewBot'
description: 'A GitHub Action to automate code review process.'
inputs:
  GEMINI_KEY:
    description: 'Gemini key'
    required: false
  GEMINI_MODEL:
    description: 'Gemini model'
    required: false
    default: 'gemini-1.5-pro-latest'
  GITHUB_TOKEN:
    description: 'GitHub token'
    required: true
  MAX_LENGTH:
    description: 'Maximum length of the code (characters) that this action will pass to the model'
    required: false
    default: '10000'
  MAX_OUTPUT_TOKENS:
    description: 'Maximum number of tokens in the output of the model'
    required: false
    default: '8192'
runs:
  using: 'node20'
  main: 'compiled/index.js'
  