name: 'ReviewBot'
description: 'A GitHub Action to automate code review process.'
inputs:
  GEMINI_KEY:
    description: 'Gemini key'
    required: false
  GEMINI_MODEL:
    description: 'Gemini model'
    required: false
    default: 'gemini-1.5-flash-latest'
  GITHUB_TOKEN:
    description: 'GitHub token'
    required: true
runs:
  using: 'node20'
  main: 'compiled/index.js'
  