name: use my action
on: 
  pull_request:

jobs:
  my_first_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      
      - name: ReviewBot Step
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
        
